arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - es
  - pt_BR
untranslated-messages-file: lib/l10n/untranslated.json