"""Initial schema

Revision ID: 25a2339a628f
Revises: dd245b139879
Create Date: 2025-09-30 13:21:35.291542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25a2339a628f'
down_revision: Union[str, Sequence[str], None] = 'dd245b139879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency_from', sa.String(), nullable=False),
    sa.Column('currency_to', sa.String(), nullable=False),
    sa.Column('amount_from', sa.Float(), nullable=False),
    sa.Column('amount_to', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('market_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_advances_id'), 'advances', ['id'], unique=False)
    op.drop_table('recipient_profiles')
    op.add_column('transactions', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('from_currency', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('to_currency', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('rate', sa.Float(), nullable=False))
    op.alter_column('transactions', 'tx_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False)
    op.drop_column('transactions', 'id')
    op.drop_column('transactions', 'relationship')
    op.drop_column('transactions', 'gateway')
    op.drop_column('transactions', 'recipient_name')
    op.drop_column('transactions', 'sender_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('recipient_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('gateway', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('relationship', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('transactions', 'tx_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transactions', 'rate')
    op.drop_column('transactions', 'to_currency')
    op.drop_column('transactions', 'from_currency')
    op.drop_column('transactions', 'user_id')
    op.create_table('recipient_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('relationship', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('recipient_profiles_pkey'))
    )
    op.drop_index(op.f('ix_advances_id'), table_name='advances')
    op.drop_table('advances')
    # ### end Alembic commands ###
