revision = '25a2339a628f'
down_revision = 'dd245b139879'

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('recipient_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('gateway', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('relationship', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('transactions', 'tx_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transactions', 'rate')
    op.drop_column('transactions', 'to_currency')
    op.drop_column('transactions', 'from_currency')
    op.drop_column('transactions', 'user_id')
    op.create_table('recipient_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('relationship', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('recipient_profiles_pkey'))
    )

    # Safe drop: ix_advances_id may already be removed by prior migration
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = [ix['name'] for ix in inspector.get_indexes('advances')]
    if 'ix_advances_id' in indexes:
        op.drop_index('ix_advances_id', table_name='advances')

    op.drop_table('advances')
    # ### end Alembic commands ###