import React, { useMemo, useState } from 'react';
import type { Beneficiary } from '../types';
import TransactionSummary from './shared/TransactionSummary';
import PaymentMethodForm, { PaymentData } from './shared/PaymentMethodForm';

type FeeSet = {
  platform?: number;
  corridor?: number;
  network?: number;
  delivery?: number;
};

type PayerAccount = {
  name: string;
  accountType: string;
  maskedNumber: string;
  token?: string;
};

type Props = {
  corridor: string;
  amount: string;
  rate: number;
  sendCurrency: string;
  receiveCurrency: string;
  fees?: FeeSet;
  beneficiary: Beneficiary;
  payerAccount?: PayerAccount;
  onBack: () => void;
  onConfirm: (
    matchStatus: 'confirmed' | 'pending',
    delivery: string,
    finalReceive: number,
    payer: PayerAccount
  ) => void;
  availableMethods?: { id: string; name: string }[];
};

export default function PaymentOptions({
  corridor,
  amount,
  rate,
  sendCurrency,
  receiveCurrency,
  fees = {},
  beneficiary,
  payerAccount,
  onBack,
  onConfirm,
  availableMethods,
}: Props) {
  const [confirmed, setConfirmed] = useState(false);
  const [useNewMethod, setUseNewMethod] = useState(false);
  
  // PaymentMethodForm state
  const [selectedMethodId, setSelectedMethodId] = useState(availableMethods?.[0]?.id || 'bank');
  const [isPaymentValid, setIsPaymentValid] = useState(false);
  const [paymentData, setPaymentData] = useState<PaymentData | null>(null);

  const sendAmount = Number.parseFloat(amount || '0') || 0;

  const totalFeesUSD = useMemo(() => {
    return (fees.platform ?? 0) + (fees.corridor ?? 0) + (fees.network ?? 0) + (fees.delivery ?? 0);
  }, [fees]);

  const finalReceive = useMemo(() => {
    return rate !== 0 ? (sendAmount - totalFeesUSD) / rate : 0;
  }, [sendAmount, totalFeesUSD, rate]);

  const effectiveRate = useMemo(() => {
    return finalReceive !== 0 ? sendAmount / finalReceive : 0;
  }, [sendAmount, finalReceive]);

  const deliverySpeed = 'instant';

  const handleConfirm = () => {
    if (!confirmed) return;
    
    let payer: PayerAccount;
    
    if (useNewMethod && paymentData) {
      payer = {
        name: paymentData.accountHolderName,
        accountType: paymentData.methodId,
        maskedNumber: paymentData.maskedNumber || 'XXXX',
        token: paymentData.token, // Secure token generated by the mock iframe
      };
    } else if (!useNewMethod && payerAccount) {
      payer = payerAccount;
    } else {
      return;
    }
    
    onConfirm('confirmed', deliverySpeed, finalReceive, payer);
  };

  const beneficiaryName = ((beneficiary as any)?.name ?? '').replace(/\s*\(.*?\)/, '') || '—';

  // Map available methods to gateways for the form
  const gateways = useMemo(() => {
    if (availableMethods && availableMethods.length > 0) {
      return availableMethods.map(m => ({
        id: m.id,
        label: m.name,
        pct: 0,
        fixed: 0
      }));
    }
    return [
      { id: 'bank', label: 'Bank Transfer', pct: 0, fixed: 0 },
      { id: 'card', label: 'Debit/Credit Card', pct: 0, fixed: 0 }
    ];
  }, [availableMethods]);

  const selectedGateway = gateways.find(g => g.id === selectedMethodId);

  return (
    <div className="space-y-6">
      <TransactionSummary 
        title="Transaction Summary"
        subtitle="Review your final terms before confirming payment."
        amount={amount}
        sourceCurrency={sendCurrency}
        amountReceived={finalReceive.toFixed(2)}
        targetCurrency={receiveCurrency}
        beneficiaryName={beneficiaryName}
        fundingMethodName={useNewMethod ? (selectedGateway?.label || '-') : (payerAccount?.accountType || '-')}
        symmetriFee={(fees.platform ?? 0).toFixed(2)}
        inboundFee={fees.network ? fees.network.toFixed(2) : undefined}
        outboundFee={(fees.delivery ?? 0).toFixed(2)}
        totalFees={totalFeesUSD.toFixed(2)}
        effectiveRate={effectiveRate.toFixed(2)}
      />

      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="px-6 py-5 border-b border-gray-200">
          <h2 className="text-xl font-bold text-gray-900">Payment Method</h2>
          <p className="text-sm text-gray-500 mt-1">How would you like to fund this transaction?</p>
        </div>
        <div className="p-6">
          {!useNewMethod && payerAccount ? (
            <div className="border border-blue-200 bg-blue-50/30 rounded-xl p-4 space-y-3">
              <p className="text-sm font-semibold text-gray-900">🏦 Saved Payer Account</p>
              <div className="flex items-center space-x-3 bg-white p-3 rounded-lg border border-gray-200">
                <div className="text-2xl">💳</div>
                <div>
                  <p className="text-sm font-bold text-gray-900">{payerAccount.name}</p>
                  <p className="text-xs text-gray-500 capitalize">{payerAccount.accountType} •••• {payerAccount.maskedNumber}</p>
                </div>
              </div>
              <button onClick={() => setUseNewMethod(true)} className="text-blue-600 font-semibold text-sm hover:underline" type="button">
                Use a different payment method
              </button>
            </div>
          ) : (
            <div className="space-y-4">
              <PaymentMethodForm 
                gateways={gateways}
                selectedMethodId={selectedMethodId}
                onMethodSelect={setSelectedMethodId}
                onDataChange={(isValid, data) => {
                  setIsPaymentValid(isValid);
                  setPaymentData(data);
                }}
              />
              {payerAccount && (
                <button onClick={() => setUseNewMethod(false)} className="text-blue-600 font-semibold text-sm hover:underline" type="button">
                  Cancel and use saved account
                </button>
              )}
            </div>
          )}

          <div className="mt-6 pt-6 border-t border-gray-100">
            <label className="flex items-start space-x-3 cursor-pointer">
              <input
                type="checkbox"
                checked={confirmed}
                onChange={(e) => setConfirmed(e.target.checked)}
                className="mt-1 w-5 h-5 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
              />
              <span className="text-sm text-gray-700 leading-snug">
                I authorize Symmetri to securely process this payment. I understand the final exchange rate reflects actual costs after platform and payment fees.
              </span>
            </label>
          </div>
        </div>
      </div>

      <div className="flex space-x-4">
        <button
          onClick={onBack}
          className="flex-1 py-4 bg-white border border-gray-300 rounded-xl font-bold text-gray-700 hover:bg-gray-50 transition-colors shadow-sm"
          type="button"
        >
          Back
        </button>
        <button
          onClick={handleConfirm}
          disabled={!confirmed || (useNewMethod && !isPaymentValid)}
          className="flex-[2] py-4 rounded-xl font-bold text-white bg-blue-600 hover:bg-blue-700 transition-colors shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
          type="button"
        >
          Confirm & Pay
        </button>
      </div>
    </div>
  );
}